In [1]:
import numpy as np

In [2]:
xAll = np.array(([2, 9], [1, 5], [3, 6], [5, 10]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

xAll = xAll / np.amax(xAll, axis=0)
y = y / 100

X = np.split(xAll, [3])[0] 
xPredicted = np.split(xAll, [3])[1]  

y = np.array(([92], [86], [89]), dtype=float)
y = y / 100


class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3

        #weights
        self.W1 = np.random.randn(
            self.inputSize,
            self.hiddenSize)  
        self.W2 = np.random.randn(
            self.hiddenSize,
            self.outputSize)

    def forward(self, X):
        
        self.z = np.dot(
            X,
            self.W1)  
        self.z2 = self.sigmoid(self.z) 
        self.z3 = np.dot(
            self.z2, self.W2
        ) 
        o = self.sigmoid(self.z3) 
        return o

    def sigmoid(self, s):
        
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
       
        return s * (1 - s)

    def backward(self, X, y, o):
       
        self.o_error = y - o 
        self.o_delta = self.o_error * self.sigmoidPrime(
            o)

        self.z2_error = self.o_delta.dot(
            self.W2.T
        )  
        self.z2_delta = self.z2_error * self.sigmoidPrime(
            self.z2) 

        self.W1 += X.T.dot(
            self.z2_delta)  
        self.W2 += self.z2.T.dot(
            self.o_delta)  

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

    def saveWeights(self):
        np.savetxt("w1.txt", self.W1, fmt="%s")
        np.savetxt("w2.txt", self.W2, fmt="%s")

    def predict(self):
        print("Predicted data based on trained weights: ")
        print("Input (scaled): \n" + str(xPredicted))
        print("Output: \n" + str(self.forward(xPredicted)))


NN = Neural_Network()
for i in range(1000): 
    print("# " + str(i) + "\n")
    print("Input (scaled): \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(NN.forward(X)))
    print("Loss: \n" +
          str(np.mean(np.square(y - NN.forward(X)))))  # mean sum squared loss
    print("\n")
    NN.train(X, y)

NN.saveWeights()
NN.predict()

# 0

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.85248777]
 [0.81885859]
 [0.85130571]]
Loss: 
0.002582588401245414


# 1

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.85561945]
 [0.82215651]
 [0.85434465]]
Loss: 
0.0022827629183264507


# 2

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.85845794]
 [0.82515455]
 [0.85710018]]
Loss: 
0.0020280093244402996


# 3

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.86104166]
 [0.827891  ]
 [0.85960932]]
Loss: 
0.001810222444557704


# 4

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.86340251]
 [0.83039776]
 [0.86190284]]
Loss: 
0.0016230061329152124


# 5

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.

 [0.89378308]]
Loss: 
0.0002058163940171662


# 52

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89630613]
 [0.86599672]
 [0.89394558]]
Loss: 
0.00020430918360886052


# 53

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89646624]
 [0.86617219]
 [0.89410139]]
Loss: 
0.00020291846806852007


# 54

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89661981]
 [0.86634047]
 [0.89425082]]
Loss: 
0.00020163476849548355


# 55

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89676715]
 [0.86650187]
 [0.89439414]]
Loss: 
0.00020044941832267707


# 56

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89690853]
 [0.86665671]
 [0.89453165]]
Loss: 
0.00019935448901416

# 113

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90006561]
 [0.87005631]
 [0.89757111]]
Loss: 
0.00018527704561360946


# 114

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90008128]
 [0.87007186]
 [0.89758554]]
Loss: 
0.00018524603478686633


# 115

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90009641]
 [0.8700868 ]
 [0.89759944]]
Loss: 
0.00018521593419715414


# 116

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90011102]
 [0.87010116]
 [0.89761282]]
Loss: 
0.0001851866781635457


# 117

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90012512]
 [0.87011496]
 [0.8976257 ]]
Loss: 
0.00018515820579321192


# 118

Input (scaled): 
[[0.4 0.9]
 



# 178

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9004909 ]
 [0.87040642]
 [0.89792713]]
Loss: 
0.00018391264223556665


# 179

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9004931 ]
 [0.87040698]
 [0.89792835]]
Loss: 
0.00018389434517264048


# 180

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90049525]
 [0.87040748]
 [0.89792952]]
Loss: 
0.0001838760591460119


# 181

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90049736]
 [0.87040793]
 [0.89793065]]
Loss: 
0.0001838577836468237


# 182

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90049942]
 [0.87040833]
 [0.89793174]]
Loss: 
0.00018383951820257947


# 183

Input (scaled): 
[[0.4 0.9]


# 246

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90058426]
 [0.87038234]
 [0.89795515]]
Loss: 
0.0001826827194682816


# 247

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90058525]
 [0.87038157]
 [0.89795519]]
Loss: 
0.0001826647856769836


# 248

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90058624]
 [0.87038079]
 [0.89795522]]
Loss: 
0.00018264685576323096


# 249

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90058722]
 [0.87038001]
 [0.89795525]]
Loss: 
0.00018262892972178293


# 250

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90058819]
 [0.87037923]
 [0.89795528]]
Loss: 
0.00018261100754764258


# 251

Input (scaled): 
[[0.4 0.9]
 [

Predicted Output: 
[[0.90064941]
 [0.87032286]
 [0.89795298]]
Loss: 
0.0001814188656196415


# 318

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90065029]
 [0.870322  ]
 [0.89795291]]
Loss: 
0.0001814011996004182


# 319

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90065118]
 [0.87032113]
 [0.89795285]]
Loss: 
0.00018138353727285535


# 320

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90065206]
 [0.87032027]
 [0.89795279]]
Loss: 
0.00018136587863498853


# 321

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90065294]
 [0.8703194 ]
 [0.89795273]]
Loss: 
0.00018134822368484364


# 322

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90065382]
 [0.

 [0.89794784]]
Loss: 
0.00018012142555307695


# 392

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90071495]
 [0.87025827]
 [0.89794776]]
Loss: 
0.00018010402749666914


# 393

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90071582]
 [0.87025741]
 [0.89794769]]
Loss: 
0.00018008663299006313


# 394

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90071669]
 [0.87025656]
 [0.89794761]]
Loss: 
0.0001800692420313855


# 395

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90071755]
 [0.8702557 ]
 [0.89794754]]
Loss: 
0.00018005185461876866


# 396

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90071842]
 [0.87025485]
 [0.89794747]]
Loss: 
0.000180034470

Predicted Output: 
[[0.90076934]
 [0.87020472]
 [0.89794295]]
Loss: 
0.0001790150289868612


# 456

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9007702 ]
 [0.87020388]
 [0.89794287]]
Loss: 
0.00017899785438629052


# 457

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90077106]
 [0.87020304]
 [0.8979428 ]]
Loss: 
0.00017898068321779345


# 458

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90077192]
 [0.87020219]
 [0.89794272]]
Loss: 
0.0001789635154795696


# 459

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90077278]
 [0.87020135]
 [0.89794264]]
Loss: 
0.00017894635116980803


# 460

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90077364]
 [0.

# 526

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90083008]
 [0.8701453 ]
 [0.89793722]]
Loss: 
0.00017780405887220067


# 527

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90083094]
 [0.87014447]
 [0.89793713]]
Loss: 
0.0001777871235215038


# 528

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90083179]
 [0.87014364]
 [0.89793705]]
Loss: 
0.00017777019147724533


# 529

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90083264]
 [0.87014281]
 [0.89793697]]
Loss: 
0.00017775326273769648


# 530

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90083349]
 [0.87014198]
 [0.89793688]]
Loss: 
0.00017773633730111774


# 531

Input (scaled): 
[[0.4 0.9]
 

Loss: 
0.00017671006342918886


# 592

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90088605]
 [0.87009092]
 [0.89793159]]
Loss: 
0.00017669333943477197


# 593

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90088689]
 [0.8700901 ]
 [0.89793151]]
Loss: 
0.00017667661863616545


# 594

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90088773]
 [0.87008928]
 [0.89793142]]
Loss: 
0.00017665990103170133


# 595

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90088858]
 [0.87008846]
 [0.89793133]]
Loss: 
0.0001766431866197089


# 596

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90088942]
 [0.87008765]
 [0.89793125]]
Loss: 
0.0001766264753985203


# 597

 [0.89]]
Predicted Output: 
[[0.90094322]
 [0.87003572]
 [0.89792552]]
Loss: 
0.00017556351849718667


# 661

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90094405]
 [0.87003492]
 [0.89792543]]
Loss: 
0.0001755470111448627


# 662

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90094489]
 [0.87003411]
 [0.89792534]]
Loss: 
0.00017553050687530648


# 663

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90094573]
 [0.87003331]
 [0.89792525]]
Loss: 
0.00017551400568691558


# 664

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90094657]
 [0.8700325 ]
 [0.89792515]]
Loss: 
0.00017549750757808288


# 665

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9009

Loss: 
0.00017459480753035956


# 720

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90099327]
 [0.86998771]
 [0.89791992]]
Loss: 
0.0001745784793428914


# 721

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9009941 ]
 [0.86998691]
 [0.89791983]]
Loss: 
0.0001745621541449771


# 722

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90099493]
 [0.86998612]
 [0.89791973]]
Loss: 
0.00017454583193506293


# 723

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90099576]
 [0.86998532]
 [0.89791964]]
Loss: 
0.00017452951271159964


# 724

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90099659]
 [0.86998453]
 [0.89791954]]
Loss: 
0.00017451319647302985


# 725

Predicted Output: 
[[0.90105367]
 [0.86993013]
 [0.89791283]]
Loss: 
0.00017339449675123064


# 794

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9010545 ]
 [0.86992934]
 [0.89791273]]
Loss: 
0.00017337838565146136


# 795

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90105532]
 [0.86992856]
 [0.89791263]]
Loss: 
0.00017336227742862983


# 796

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90105614]
 [0.86992778]
 [0.89791253]]
Loss: 
0.00017334617208125412


# 797

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90105697]
 [0.869927  ]
 [0.89791243]]
Loss: 
0.00017333006960783541


# 798

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90105779]
 [

# 856

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90110539]
 [0.86988115]
 [0.89790644]]
Loss: 
0.000172385057458265


# 857

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90110621]
 [0.86988038]
 [0.89790634]]
Loss: 
0.00017236912472879434


# 858

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90110703]
 [0.86987961]
 [0.89790624]]
Loss: 
0.00017235319478401152


# 859

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90110785]
 [0.86987884]
 [0.89790613]]
Loss: 
0.00017233726762247697


# 860

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90110866]
 [0.86987806]
 [0.89790603]]
Loss: 
0.00017232134324275195


# 861

Input (scaled): 
[[0.4 0.9]
 [

# 916

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90115431]
 [0.86983511]
 [0.89790015]]
Loss: 
0.00017143397375628117


# 917

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90115512]
 [0.86983435]
 [0.89790004]]
Loss: 
0.00017141820558949435


# 918

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90115593]
 [0.86983359]
 [0.89789994]]
Loss: 
0.0001714024401225029


# 919

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90115674]
 [0.86983282]
 [0.89789983]]
Loss: 
0.00017138667735391684


# 920

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90115756]
 [0.86983206]
 [0.89789972]]
Loss: 
0.0001713709172823437


# 921

Input (scaled): 
[[0.4 0.9]
 [

# 977

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9012037 ]
 [0.86978889]
 [0.89789354]]
Loss: 
0.00017047700654774814


# 978

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90120451]
 [0.86978813]
 [0.89789343]]
Loss: 
0.0001704614005506185


# 979

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90120532]
 [0.86978738]
 [0.89789332]]
Loss: 
0.00017044579716984213


# 980

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90120612]
 [0.86978663]
 [0.89789321]]
Loss: 
0.00017043019640406145


# 981

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90120693]
 [0.86978587]
 [0.8978931 ]]
Loss: 
0.0001704145982519437


# 982

Input (scaled): 
[[0.4 0.9]
 [