In [7]:
import numpy as np
import pandas as pd

### 1: Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [8]:
x = np.array([3, 5])
y = np.array([2, 5])
print(x)
print(y)
print("Greater")
print(np.greater(x, y))
print("Greater_equal")
print(np.greater_equal(x, y))
print("Less")
print(np.less(x, y))
print("Less_equal")
print(np.less_equal(x, y))


[3 5]
[2 5]
Greater
[ True False]
Greater_equal
[ True  True]
Less
[False False]
Less_equal
[False  True]


### 2: Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [9]:
arr_zero=np.zeros(10)
print("An array of 10 zeros:")
print(arr_zero)
arr_tens=np.ones(10)
print("An array of 10 ones:")
print(arr_tens)
arr_five=np.ones(10)*5
print("An array of 10 fives:")
print(arr_five)


An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### 3:Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of agiven array


In [10]:
x = np.array([[1,3],[4,6]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[1 3]
 [4 6]]
Sum of all elements:
14
Sum of each column:
[5 9]
Sum of each row:
[ 4 10]


### 4:Write a NumPy program to add, subtract, multiply, divide arguments element-wise

In [11]:
print("Add:")
print(np.add(1.0, 4.0))
print("Subtract:")
print(np.subtract(1.0, 4.0))
print("Multiply:")
print(np.multiply(1.0, 4.0))
print("Divide:")
print(np.divide(1.0, 4.0))


Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25


### 5:Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.


In [13]:
print("sine")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cosine")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tangent")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))


sine
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


### 6:Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels

In [18]:
bank_details  = {'Name': ['Shubham','Tejal','Lokesh','Zeshan','Raghav','Alok'],
        'Amount': [1000,122,1200,1400,1230,1345]}
        
S_No = ['a', 'b', 'c', 'd', 'e', 'f']

df = pd.DataFrame(bank_details , index=S_No)
print(df)


      Name  Amount
a  Shubham    1000
b    Tejal     122
c   Lokesh    1200
d   Zeshan    1400
e   Raghav    1230
f     Alok    1345


### 7:Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [22]:
cricket_data  = {'Name': ['Shubham','Tejal','Lokesh','Zeshan','Raghav','Alok'],
                 'REsult': ['Win','Lose','Win','Lose','Win','Lose'],
        'Score': [100,12,12,14,123,15]}
        
S_No = ['a', 'b', 'c', 'd', 'e', 'f']
df = pd.DataFrame(cricket_data , index=S_No)
print(df[['Name', 'Score']])

      Name  Score
a  Shubham    100
b    Tejal     12
c   Lokesh     12
d   Zeshan     14
e   Raghav    123
f     Alok     15


### 8:Write a Pandas program to join the two given dataframes along rows and assign all data

In [25]:
bank_details  = pd.DataFrame({'Name': ['Shubham','Tejal','Lokesh','Zeshan','Raghav','Alok'],
        'Amount': [1000,122,1200,1400,1230,1345]})
cricket_data  = pd.DataFrame({'Name': ['Shubham','Tejal','Lokesh','Zeshan','Raghav','Alok'],
                 'REsult': ['Win','Lose','Win','Lose','Win','Lose'],
        'Score': [100,12,12,14,123,15]})
result_data = pd.concat([bank_details, cricket_data])
print(result_data)

      Name  Amount REsult  Score
0  Shubham  1000.0    NaN    NaN
1    Tejal   122.0    NaN    NaN
2   Lokesh  1200.0    NaN    NaN
3   Zeshan  1400.0    NaN    NaN
4   Raghav  1230.0    NaN    NaN
5     Alok  1345.0    NaN    NaN
0  Shubham     NaN    Win  100.0
1    Tejal     NaN   Lose   12.0
2   Lokesh     NaN    Win   12.0
3   Zeshan     NaN   Lose   14.0
4   Raghav     NaN    Win  123.0
5     Alok     NaN   Lose   15.0


### 9.Write a Pandas program to detect missing values of a given DataFrame. Display True or False.


In [26]:
print(result_data.isna())

    Name  Amount  REsult  Score
0  False   False    True   True
1  False   False    True   True
2  False   False    True   True
3  False   False    True   True
4  False   False    True   True
5  False   False    True   True
0  False    True   False  False
1  False    True   False  False
2  False    True   False  False
3  False    True   False  False
4  False    True   False  False
5  False    True   False  False


### 10.Write a Pandas program to create and display a one-dimensional array-like object containing an array of data.

In [27]:
ds = pd.Series([5,10,15,20,25,30])
print(ds)

0     5
1    10
2    15
3    20
4    25
5    30
dtype: int64
